Write test for assignment example
gustavclausen/chord-p2p-network pull request #3
Opened 2018-11-18 15:36 UTC by runeksvendsen

https://learnit.itu.dk/mod/assign/view.php?id=92747

2018-11-18 18:33 UTC, gustavclausen requested changes

2018-11-18 18:33 UTC, gustavclausen commented on src/main/java/Peer.java
> +            } finally {
Kan vi ikke bare:

```suggestion
            } finally {
               abort();
            }
```

2018-11-18 18:33 UTC, gustavclausen commented on src/main/java/clients/GetClient.java
> +    // public static void get(String[] programArguments) {
Denne kommentar må meget gerne fjernes 😄

2018-11-18 19:26 UTC, runeksvendsen commented on src/main/java/Peer.java
> +            } finally {
Godt fanget :)

2018-11-18 19:27 UTC, runeksvendsen commented on src/main/java/clients/GetClient.java
> +    // public static void get(String[] programArguments) {
Hovsa 😬

2018-11-19 08:09 UTC, gustavclausen approved these changes

2018-11-19 08:10 UTC, merged